### ISSUE TITLE
Bug report: damage teleports you back to spawn

### ISSUE THREAD

**Issue by lhridder** [Wqrld/FeroxCore#3]
Hi i've been playing with this plugin on my minecraft server but it seems to have a big problem.
**Environment**
> openjdk version "1.8.0_282"
> OpenJDK Runtime Environment (build 1.8.0_282-b08)
> OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

> Server software: [21:29:10 INFO]: This server is running CraftBukkit version git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

> Plugins: [21:28:34 INFO]: Plugins (22): AdvancedTabOverlay, AnimatedNames, ClientDetector, Essentials, FastAsyncWorldEdit, FeatherBoard, FeroxCore, LiteBans, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI, NametagEdit, PlaceholderAPI, PlugMan, ProtocolLib, ServerListMotdSpigot, SimpleRename, Vault, ViaRewind, ViaVersion, VoidGenerator, WorldEdit

**Problem description**
When playing the game and taking damage while being in spectator gamemode the plugin seems to cause a malfeasance in events firing, as all damage will teleport you back to the spectator spawn, this includes falldamage and player to player damage. Please take a look at the video i've sent below to see a demonstration of this grave error in programming.

**Maps affected:**
- Sphinx
- Castle
- Sahara
- Fallen

**Errors in console**
> [21:15:29 WARN]: [Multiverse-Core] Task #5936 for Multiverse-Core v4.1.1-1.8.8-SNAPSHOT-b4 generated an exception
> java.lang.IllegalStateException: Lost reference to bukkit world 'world2'
> at com.onarandombox.MultiverseCore.MVWorld.getCBWorld(MVWorld.java:509) ~[?:?]
> at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$2.run(MVPlayerListener.java:357) ~[?:?]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:893) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [21:15:29 WARN]: [Multiverse-Core] Task #5937 for Multiverse-Core v4.1.1-1.8.8-SNAPSHOT-b4 generated an exception
> java.lang.IllegalStateException: Lost reference to bukkit world 'world2'
> at com.onarandombox.MultiverseCore.MVWorld.getCBWorld(MVWorld.java:509) ~[?:?]
> at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$2.run(MVPlayerListener.java:357) ~[?:?]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:893) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [21:15:29 WARN]: [Multiverse-Core] Task #5938 for Multiverse-Core v4.1.1-1.8.8-SNAPSHOT-b4 generated an exception
> java.lang.IllegalStateException: Lost reference to bukkit world 'world2'
> at com.onarandombox.MultiverseCore.MVWorld.getCBWorld(MVWorld.java:509) ~[?:?]
> at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$2.run(MVPlayerListener.java:357) ~[?:?]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:893) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724) [patched_1.8.8.jar:git-SportPaper-92c8b95-P.c67d9f4-SP.233af53-CB.c2e0bbd]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Visual evidence**
https://user-images.githubusercontent.com/63594063/146993294-c8cd7f8a-649e-4f77-a29e-af6464862c3b.mp4

**Other issues**
- Spawning in the void
- Spawning in the main world
- Scoreboard having strange spacers every now and then
- Players having blinking names (their name switches from color)
- The 2nd map after restarting is always broken because you continually fall into the void
- You sometimes spawn in the old map
- You can build outside arena bounds
- You can see the normal world outside arena bounds
- You can kill spectators
- Clones appear of players
- Gametime in the tablist will increase when there's no active game
- Stats are reset randomly

**Comment by Wqrld** [comment]
Issue between computer and chair

**Comment by Jarco-dev** [comment]
> Issue between computer and chair

Your computer and chair?

**Comment by Wqrld** [comment]
fixed, fuck java
